# Generated by Django 5.2.4 on 2025-08-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tribe_village_remove_schemebenefit_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='tribe',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='village',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
