# Generated by Django 5.2.4 on 2025-08-10 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tribe_tribe_alter_village_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribalmember',
            name='tribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tribe'),
        ),
    ]
