# Generated by Django 5.2.4 on 2025-08-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribalmember',
            name='gender',
            field=models.CharField(default='NA', max_length=3),
        ),
    ]
