# Generated by Django 5.2.4 on 2025-08-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tribalmember_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perm',
            field=models.BooleanField(default=False),
        ),
    ]
