# Generated by Django 5.2.4 on 2025-08-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TribeUser',
        ),
    ]
