# Generated by Django 5.2.4 on 2025-08-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_mangementroles_mangementuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangementroles',
            name='role',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
