# Generated by Django 5.2.4 on 2025-08-15 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schemes'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.village'),
        ),
    ]
